name: Validate Action Examples

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  validate-examples:
    uses: devops-actions/.github/.github/workflows/actions-example-checker.yml@e537f6767594e8d4cfff18edf24e5b4e899b0e51 # main
    permissions:
      contents: read